                  List of relations
 Schema |            Name            | Type  | Owner  
--------+----------------------------+-------+--------
 public | acknowledges               | table | zabbix
 public | actions                    | table | zabbix
 public | alerts                     | table | zabbix
 public | auditlog                   | table | zabbix
 public | autoreg_host               | table | zabbix
 public | changelog                  | table | zabbix
 public | conditions                 | table | zabbix
 public | config                     | table | zabbix
 public | config_autoreg_tls         | table | zabbix
 public | connector                  | table | zabbix
 public | connector_tag              | table | zabbix
 public | corr_condition             | table | zabbix
 public | corr_condition_group       | table | zabbix
 public | corr_condition_tag         | table | zabbix
 public | corr_condition_tagpair     | table | zabbix
 public | corr_condition_tagvalue    | table | zabbix
 public | corr_operation             | table | zabbix
 public | correlation                | table | zabbix
 public | dashboard                  | table | zabbix
 public | dashboard_page             | table | zabbix
 public | dashboard_user             | table | zabbix
 public | dashboard_usrgrp           | table | zabbix
 public | dbversion                  | table | zabbix
 public | dchecks                    | table | zabbix
 public | dhosts                     | table | zabbix
 public | drules                     | table | zabbix
 public | dservices                  | table | zabbix
 public | escalations                | table | zabbix
 public | event_recovery             | table | zabbix
 public | event_suppress             | table | zabbix
 public | event_symptom              | table | zabbix
 public | event_tag                  | table | zabbix
 public | events                     | table | zabbix
 public | expressions                | table | zabbix
 public | functions                  | table | zabbix
 public | globalmacro                | table | zabbix
 public | globalvars                 | table | zabbix
 public | graph_discovery            | table | zabbix
 public | graph_theme                | table | zabbix
 public | graphs                     | table | zabbix
 public | graphs_items               | table | zabbix
 public | group_discovery            | table | zabbix
 public | group_prototype            | table | zabbix
 public | ha_node                    | table | zabbix
 public | hgset                      | table | zabbix
 public | hgset_group                | table | zabbix
 public | history                    | table | zabbix
 public | history_bin                | table | zabbix
 public | history_log                | table | zabbix
 public | history_str                | table | zabbix
 public | history_text               | table | zabbix
 public | history_uint               | table | zabbix
 public | host_discovery             | table | zabbix
 public | host_hgset                 | table | zabbix
 public | host_inventory             | table | zabbix
 public | host_proxy                 | table | zabbix
 public | host_rtdata                | table | zabbix
 public | host_tag                   | table | zabbix
 public | hostmacro                  | table | zabbix
 public | hosts                      | table | zabbix
 public | hosts_groups               | table | zabbix
 public | hosts_templates            | table | zabbix
 public | housekeeper                | table | zabbix
 public | hstgrp                     | table | zabbix
 public | httpstep                   | table | zabbix
 public | httpstep_field             | table | zabbix
 public | httpstepitem               | table | zabbix
 public | httptest                   | table | zabbix
 public | httptest_field             | table | zabbix
 public | httptest_tag               | table | zabbix
 public | httptestitem               | table | zabbix
 public | icon_map                   | table | zabbix
 public | icon_mapping               | table | zabbix
 public | ids                        | table | zabbix
 public | images                     | table | zabbix
 public | interface                  | table | zabbix
 public | interface_discovery        | table | zabbix
 public | interface_snmp             | table | zabbix
 public | item_condition             | table | zabbix
 public | item_discovery             | table | zabbix
 public | item_parameter             | table | zabbix
 public | item_preproc               | table | zabbix
 public | item_rtdata                | table | zabbix
 public | item_rtname                | table | zabbix
 public | item_tag                   | table | zabbix
 public | items                      | table | zabbix
 public | lld_macro_path             | table | zabbix
 public | lld_override               | table | zabbix
 public | lld_override_condition     | table | zabbix
 public | lld_override_opdiscover    | table | zabbix
 public | lld_override_operation     | table | zabbix
 public | lld_override_ophistory     | table | zabbix
 public | lld_override_opinventory   | table | zabbix
 public | lld_override_opperiod      | table | zabbix
 public | lld_override_opseverity    | table | zabbix
 public | lld_override_opstatus      | table | zabbix
 public | lld_override_optag         | table | zabbix
 public | lld_override_optemplate    | table | zabbix
 public | lld_override_optrends      | table | zabbix
 public | maintenance_tag            | table | zabbix
 public | maintenances               | table | zabbix
 public | maintenances_groups        | table | zabbix
 public | maintenances_hosts         | table | zabbix
 public | maintenances_windows       | table | zabbix
 public | media                      | table | zabbix
 public | media_type                 | table | zabbix
 public | media_type_message         | table | zabbix
 public | media_type_param           | table | zabbix
 public | mfa                        | table | zabbix
 public | mfa_totp_secret            | table | zabbix
 public | module                     | table | zabbix
 public | opcommand                  | table | zabbix
 public | opcommand_grp              | table | zabbix
 public | opcommand_hst              | table | zabbix
 public | opconditions               | table | zabbix
 public | operations                 | table | zabbix
 public | opgroup                    | table | zabbix
 public | opinventory                | table | zabbix
 public | opmessage                  | table | zabbix
 public | opmessage_grp              | table | zabbix
 public | opmessage_usr              | table | zabbix
 public | optag                      | table | zabbix
 public | optemplate                 | table | zabbix
 public | permission                 | table | zabbix
 public | problem                    | table | zabbix
 public | problem_tag                | table | zabbix
 public | profiles                   | table | zabbix
 public | proxy                      | table | zabbix
 public | proxy_autoreg_host         | table | zabbix
 public | proxy_dhistory             | table | zabbix
 public | proxy_group                | table | zabbix
 public | proxy_group_rtdata         | table | zabbix
 public | proxy_history              | table | zabbix
 public | proxy_rtdata               | table | zabbix
 public | regexps                    | table | zabbix
 public | report                     | table | zabbix
 public | report_param               | table | zabbix
 public | report_user                | table | zabbix
 public | report_usrgrp              | table | zabbix
 public | rights                     | table | zabbix
 public | role                       | table | zabbix
 public | role_rule                  | table | zabbix
 public | scim_group                 | table | zabbix
 public | script_param               | table | zabbix
 public | scripts                    | table | zabbix
 public | service_alarms             | table | zabbix
 public | service_problem            | table | zabbix
 public | service_problem_tag        | table | zabbix
 public | service_status_rule        | table | zabbix
 public | service_tag                | table | zabbix
 public | services                   | table | zabbix
 public | services_links             | table | zabbix
 public | sessions                   | table | zabbix
 public | sla                        | table | zabbix
 public | sla_excluded_downtime      | table | zabbix
 public | sla_schedule               | table | zabbix
 public | sla_service_tag            | table | zabbix
 public | sysmap_element_trigger     | table | zabbix
 public | sysmap_element_url         | table | zabbix
 public | sysmap_shape               | table | zabbix
 public | sysmap_url                 | table | zabbix
 public | sysmap_user                | table | zabbix
 public | sysmap_usrgrp              | table | zabbix
 public | sysmaps                    | table | zabbix
 public | sysmaps_element_tag        | table | zabbix
 public | sysmaps_elements           | table | zabbix
 public | sysmaps_link_triggers      | table | zabbix
 public | sysmaps_links              | table | zabbix
 public | tag_filter                 | table | zabbix
 public | task                       | table | zabbix
 public | task_acknowledge           | table | zabbix
 public | task_check_now             | table | zabbix
 public | task_close_problem         | table | zabbix
 public | task_data                  | table | zabbix
 public | task_remote_command        | table | zabbix
 public | task_remote_command_result | table | zabbix
 public | task_result                | table | zabbix
 public | timeperiods                | table | zabbix
 public | token                      | table | zabbix
 public | trends                     | table | zabbix
 public | trends_uint                | table | zabbix
 public | trigger_depends            | table | zabbix
 public | trigger_discovery          | table | zabbix
 public | trigger_queue              | table | zabbix
 public | trigger_tag                | table | zabbix
 public | triggers                   | table | zabbix
 public | ugset                      | table | zabbix
 public | ugset_group                | table | zabbix
 public | user_scim_group            | table | zabbix
 public | user_ugset                 | table | zabbix
 public | userdirectory              | table | zabbix
 public | userdirectory_idpgroup     | table | zabbix
 public | userdirectory_ldap         | table | zabbix
 public | userdirectory_media        | table | zabbix
 public | userdirectory_saml         | table | zabbix
 public | userdirectory_usrgrp       | table | zabbix
 public | users                      | table | zabbix
 public | users_groups               | table | zabbix
 public | usrgrp                     | table | zabbix
 public | valuemap                   | table | zabbix
 public | valuemap_mapping           | table | zabbix
 public | widget                     | table | zabbix
 public | widget_field               | table | zabbix
(203 rows)

